import type { Metadata } from "next";
import { NotoSansKR, Unbatang } from "@/common";

import "./globals.css";

import Image from "next/image";
import { ReactQueryClientProvider } from "@/common/services";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${NotoSansKR.variable} ${Unbatang.variable}`}>
      <body>
        <SessionProvider>
          <ReactQueryClientProvider>
            <div className="h-screen w-screen bg-primary transition-colors ease-in-out animate-bg-to-secondary">
              <div className="grid grid-cols-[3fr_360px_1fr] h-full">
                <div className="size-full flex justify-center items-center">
                  <div className="flex flex-col justify-center items-center gap-[18px]">
                    <Image
                      src="/icon/logo.svg"
                      alt="logo"
                      width={48}
                      height={48}
                      className="animate-fade-in"
                    />
                    <div className="text-primary text-sm font-unbatang">
                      책과 공간 , 인연의 서사
                    </div>
                  </div>
                </div>
                <div
                  className="h-full bg-white relative overflow-hidden"
                  id="mobile-area"
                >
                  {children}
                  <div id="dialog-root" />
                </div>
                <div />
              </div>
            </div>
          </ReactQueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
